services:
  backend:
    build: .
    container_name: hardware-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["PYTHONPATH=src", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
